site_name: mkdockyard

plugins:
- mkdockyard:
    repos:
      - url: "https://github.com/Textualize/textual.git"
        ref: "main"
      - url: "https://github.com/Textualize/rich.git"
        ref: "master"
      - url: "https://github.com/pydantic/pydantic.git"
        ref: "main"
- mkdocstrings:
